services:
  ksmserver:
    build:
      context: .
      dockerfile: Dockerfile
    ports: 
      - 8080:8080
    environment:
      KSM_ART_PATH: "/mnt/ksm/art" 
      KSM_DAT_PATH: "/mnt/ksm/data" 
      TIMEZONE: "Europe/Stockholm"
    volumes:
      - /mnt/testksm:/mnt/ksm
    networks:
      backnet:
networks:
  backnet: 
